@startuml
'https://plantuml.com/class-diagram

class Championnat {
-nom : String

ajouterEquipe(equipe : Equipe) : void
getNombreEquipes() : int
}

class Equipe {
-nom : String
-nombreLike : Integer
}

Championnat --> "0..*" Equipe

@enduml